# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblName',
            fields=[
                ('locker_id', models.IntegerField(primary_key=True, serialize=False)),
                ('locker_name', models.CharField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=36, null=True)),
                ('state', models.CharField(blank=True, max_length=28, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('locker_capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TBL_NAME',
            },
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
