# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170108_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblname',
            options={},
        ),
    ]
